### ISSUE TITLE
Obtain dataset

### ISSUE THREAD

**Issue by LairChen** [hachreak/movad#3]
I can't get the dataset provided by the original author because of network problems，Could you provide your collated dataset？Thank you very much. It's very important to me.

**Comment by hachreak** [comment]
Hi @LairChen 
you can find the [dataset here](https://univpr-my.sharepoint.com/:f:/g/personal/leonardo_rossi_unipr_it/EucrhGOY6YdAhF2CqjuwcAIBrejxims0dlNOvLIFdnTPXg?e=IGoROh).
Please, let me know if you can download DoTA dataset from the link.

**Comment by LairChen** [comment]
Thanks very much, I can download the dataset from this link.
