### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by LairChen** [hachreak/movad#4]
How to benchmark detection accuracy (AUC) for non-ego anomaly categories?

**Comment by hachreak** [comment]
Hi @LairChen ,
sorry for the late reply.
Have you tried to enable the `--machine_reading` from CLI?
If I remember correctly, it show metrics for [non-ego only](https://github.com/hachreak/movad/blob/main/src/metrics.py#L48-L49) when machine reading is enabled.

Please try:
```
python src/main.py --config cfgs/v4_2.yml --output output/v4_2/ --phase test --epoch 690 --machine_reading
```

And let me know if it works! :smile:
